#!/usr/bin/env bash
set -euo pipefail

# uat.sh — ship a BETA build to internal testers (TestFlight + Play internal) and cut a
# GitHub PRERELEASE tag. Same fundamental as scripts/release.sh (build locally, generate
# grouped release notes, tag on GitHub) — but flavored as a beta:
#
#   * Beta version = <current package.json version>-beta.<N> (e.g. 0.0.102-beta.1). N
#     auto-increments from the last matching prerelease tag. The MARKETING version is NOT
#     bumped — a beta is a pre-release OF the current version. release.sh owns the real
#     version bump once a beta is approved.
#   * Store build number (Android versionCode / iOS CURRENT_PROJECT_VERSION) = unix
#     timestamp, so every TestFlight / Play upload is unique + increasing.
#   * iOS MARKETING_VERSION stays plain numeric (App Store rejects "-beta"); the beta label
#     lives in the git tag, the Android versionName, and the store release notes.
#   * Release notes are generated FROM THE COMMITS by `claude -p` (falls back to a grouped
#     commit list), and pushed to TestFlight (What to Test) + Play internal + the GH release.
#
# Usage: scripts/uat.sh [--ios|--android]   (no arg = both)
#
# Build → upload → THEN commit/tag/push, so a failed build never leaves a dangling tag.
# Credentials come from fastlane/.env (see fastlane/.env.example). On a Mac whose keychain
# already holds the distribution cert, export SKIP_KEYCHAIN_IMPORT=1.

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BOLD='\033[1m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

DO_IOS=1; DO_ANDROID=1
case "${1:-}" in
  --ios) DO_ANDROID=0 ;; --android) DO_IOS=0 ;; "" ) ;;
  * ) error "Unknown arg '$1'. Use --ios, --android, or no arg for both." ;;
esac

# ── pre-flight ─────────────────────────────────────────────────────
command -v node   >/dev/null || error "node not installed"
command -v gh     >/dev/null || error "gh CLI not installed"
command -v bundle >/dev/null || error "bundler not installed (bundle install)"
[ -f fastlane/Fastfile ]     || error "fastlane/Fastfile not found"
[ -z "$(git status --porcelain)" ] || error "Working tree is dirty. Commit or stash first."
[ "$DO_ANDROID" = 0 ] || { [ -f android/gradlew ] || error "android/gradlew not found"; [ -n "${ANDROID_HOME:-}" ] || error "ANDROID_HOME not set"; }
[ "$DO_IOS" = 0 ]     || command -v xcodebuild >/dev/null || error "xcodebuild not installed"

# ── compute the beta version ───────────────────────────────────────
BASE_VERSION=$(node -p "require('./package.json').version")   # e.g. 0.0.102
git fetch --tags --quiet || true
LAST_N=$(git tag -l "v${BASE_VERSION}-beta.*" | sed -E "s/.*-beta\.([0-9]+)$/\1/" | sort -n | tail -1)
N=$(( ${LAST_N:-0} + 1 ))
BETA_VERSION="${BASE_VERSION}-beta.${N}"
TAG="v${BETA_VERSION}"
BUILD_NUMBER=$(date +%s)
info "Beta build: ${BOLD}${BETA_VERSION}${NC} (build ${BUILD_NUMBER}) — pre-release of ${BASE_VERSION}"

# ── apply the build-number / beta-versionName bump (working tree; committed only on success) ──
if [ "$DO_ANDROID" = 1 ]; then
  sed -i '' "s/versionCode .*/versionCode $BUILD_NUMBER/" android/app/build.gradle
  sed -i '' "s/versionName .*/versionName \"$BETA_VERSION\"/" android/app/build.gradle
fi
if [ "$DO_IOS" = 1 ]; then
  # MARKETING_VERSION stays the plain numeric BASE (App Store rejects -beta); build number bumps.
  sed -i '' "s/CURRENT_PROJECT_VERSION = .*/CURRENT_PROJECT_VERSION = $BUILD_NUMBER;/" ios/OffgridMobile.xcodeproj/project.pbxproj
fi
restore_tree() { git checkout -- android/app/build.gradle ios/OffgridMobile.xcodeproj/project.pbxproj 2>/dev/null || true; }
trap 'restore_tree' EXIT

# ── generate release notes from commits (claude -p, else grouped fallback) ──
LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
RANGE=${LAST_TAG:+${LAST_TAG}..HEAD}
COMMITS=$(git log ${RANGE:-HEAD~30..HEAD} --pretty=format:"%s (%h)" --no-merges 2>/dev/null || git log --pretty=format:"%s (%h)" --no-merges -30)
NOTES_FILE="$ROOT_DIR/uat-notes-${BUILD_NUMBER}.md"

gen_notes_with_claude() {
  command -v claude >/dev/null || return 1
  printf '%s\n' "$COMMITS" | claude -p \
"Turn these git commits into concise user-facing beta release notes for testers of Off Grid AI (a private on-device AI app). Group under short markdown headings (Features / Fixes / Improvements). One bullet per user-visible change, plain language, focus on the outcome. Follow the brand voice: no em dashes, no exclamation marks, no words like revolutionary/seamlessly/robust. Output ONLY the markdown, no preamble." \
    2>/dev/null
}

if NOTES=$(gen_notes_with_claude) && [ -n "$NOTES" ]; then
  printf '%s\n' "$NOTES" > "$NOTES_FILE"
  info "Release notes generated by claude -p"
else
  warn "claude -p unavailable/failed — falling back to a grouped commit list"
  {
    echo "## ${BETA_VERSION}"; echo ""
    printf '%s\n' "$COMMITS" | grep -iE "^feat" | sed 's/^/- /' | { grep . && echo "" || true; }
    printf '%s\n' "$COMMITS" | grep -iE "^fix"  | sed 's/^/- /' | { grep . && echo "" || true; }
    printf '%s\n' "$COMMITS" | grep -ivE "^(feat|fix|chore|test|docs|ci|refactor)" | sed 's/^/- /'
  } > "$NOTES_FILE"
fi
export UAT_CHANGELOG_PATH="$NOTES_FILE"
info "Notes:"; sed 's/^/    /' "$NOTES_FILE"; echo ""

# ── build + upload (fastlane beta lanes; they read UAT_CHANGELOG_PATH) ──
if [ "$DO_ANDROID" = 1 ]; then info "Android → Play internal…"; bundle exec fastlane android beta; fi
if [ "$DO_IOS" = 1 ];     then info "iOS → TestFlight…";        bundle exec fastlane ios beta;     fi

# ── success → commit the bump, cut the PRERELEASE tag, GH prerelease ──
trap - EXIT   # keep the bump now that the build shipped
FILES=(); [ "$DO_ANDROID" = 1 ] && FILES+=(android/app/build.gradle)
[ "$DO_IOS" = 1 ] && FILES+=(ios/OffgridMobile.xcodeproj/project.pbxproj)
git add "${FILES[@]}"
git commit -m "chore(beta): ${BETA_VERSION} (build ${BUILD_NUMBER}) [skip ci]"
git tag -a "$TAG" -m "Off Grid ${BETA_VERSION}"
git push && git push origin "$TAG"

GH_ARGS=(); [ "$DO_ANDROID" = 1 ] && [ -f android/app/build/outputs/bundle/release/app-release.aab ] && \
  { cp android/app/build/outputs/bundle/release/app-release.aab "$ROOT_DIR/OffgridMobile-${BETA_VERSION}.aab"; GH_ARGS+=("$ROOT_DIR/OffgridMobile-${BETA_VERSION}.aab"); }
gh release create "$TAG" "${GH_ARGS[@]}" --prerelease --title "Off Grid ${BETA_VERSION} (beta)" --notes-file "$NOTES_FILE"

rm -f "$NOTES_FILE" "$ROOT_DIR/OffgridMobile-${BETA_VERSION}.aab"
echo ""
info "${BOLD}Beta ${BETA_VERSION} shipped.${NC}"
[ "$DO_IOS" = 1 ]     && info "  iOS:     TestFlight (App Store Connect → TestFlight)"
[ "$DO_ANDROID" = 1 ] && info "  Android: Play Console → Internal testing"
info "  GitHub:  $(gh release view "$TAG" --json url -q .url 2>/dev/null)"
info "Approve the beta, then run scripts/release.sh to cut the real version to production."
